### ISSUE TITLE
add new component

### ISSUE THREAD

**Issue by RezMosa** [CommunitySolidServer/hello-world-component#2]
Hi, I really appreciate your advice on the issue I am facing in adding a new component into Community Solid Server. I followed your previous advice and Hello World example to inject a new sample component into CSS. I set the following config for my new component:
```json
{
  "@context": [
    "https://linkedsoftwaredependencies.org/bundles/npm/@solid/community-server/^5.0.0/components/context.jsonld",
    "https://linkedsoftwaredependencies.org/bundles/npm/hello-world-module/^5.0.0/components/context.jsonld"
  ],
  "@graph": [
    {
      "comment": "SearchListener",
      "@id": "urn:my-hello-world:core:SearchListener",
      "@type": "RouterHandler",
      "args_baseUrl": {
        "@id": "urn:solid-server:default:variable:baseUrl"
      },
      "args_targetExtractor": {
        "@id": "urn:solid-server:default:TargetExtractor"
      },
      "args_allowedMethods": [
        "*"
      ],
      "args_allowedPathNames": [
        "/query"
      ],
      "args_handler": {
        "@type": "SearchListener",
        "providerFactory": {
          "@id": "urn:solid-server:default:IdentityProviderFactory"
        }
      }
    }
  ]
}
```

Unfortunately when I request my sample component, the request is redirected to CSS setup and CSS setup home page will be displayed. Do you know what is wrong in my config please? 

Thank you so much for your help.

**Comment by joachimvh** [comment]
This is not the configuration you use to start up the server though, this is the configuration of your component, which you would then import into the actual configuration such as is done here: https://github.com/CommunitySolidServer/hello-world-component/blob/d6ada91b5f24cfeeb61cfaade787788b863a179d/hello-world-file.json#L38

I'm going to assume that is what you did. Now, the reason why you get redirected to the setup is because of the following line: https://github.com/CommunitySolidServer/hello-world-component/blob/d6ada91b5f24cfeeb61cfaade787788b863a179d/hello-world-file.json#L9

This import makes it so that setup is required when starting up the server. You can disable it by changing the import to one of the other options which you can find here: https://github.com/CommunitySolidServer/CommunitySolidServer/tree/main/config/app#setup. You probably want to change it to `disabled.json`. Or you could keep it as it is and complete the setup, after that your server would also work as expected.

Some more information about how the configurations work can be found at https://github.com/CommunitySolidServer/tutorials/blob/main/custom-configurations.md. There is also a tool now that can be used to generate configurations: https://communitysolidserver.github.io/configuration-generator/

**Comment by RezMosa** [comment]
Hello I completed the injection of my new component into CSS through using Component.js and using your guideline. Thanks for that. When I run my new component, It will be run with a new CSS. 
I have an old local CSS (without injected new component) that includes some PODs and is running in my machine. 
My concern is how to run my new injected component with the old CSS that is running now? I don't want to lose my data resources in old CSS. Thanks for your help.
